name: Build and Push Docker Image

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:     # caller must pass these
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: luizscofield/sample-python-app:${{ env.SHORT_SHA }}

      - name: Set image-tag output
        id: set-output
        run: |
          echo "image-tag=${{ env.SHORT_SHA }}" >> $GITHUB_OUTPUT