name: Deploy Docker Image to EC2 Instance

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      AWS_INSTANCE_ID:
        required: true
      S3_BUCKET:
        required: true

jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Update docker-compose file
        run: |
          sed -i "s/{replaced-by-github-actions}/${{ env.SHORT_SHA }}/g" docker-compose.yml
          cat docker-compose.yml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload docker-compose file to S3 bucket
        run: |
          aws s3 cp docker-compose.yml s3://${{ secrets.S3_BUCKET }}/docker-compose.yml
