name: Terraform Plan on PR

on:
  pull_request:

jobs:
  terraform:
    uses: ./.github/workflows/templates/terraform-plan.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      terraform_version: ${{ vars.TERRAFORM_VERSION }}