name: Terraform Plan

on:
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan -no-color
        working-directory: ./terraform

      - name: Show plan (json)
        run: terraform show -json terraform.plan > terraform.json
        working-directory: ./terraform

      - name: Show plan (text)
        run: terraform show -no-color terraform.plan > terraform.text
        working-directory: ./terraform

      - uses: ahmadnassri/action-terraform-report@v4
        with:
          terraform-text: ${{ github.workspace }}/terraform/terraform.text
          terraform-json: ${{ github.workspace }}/terraform/terraform.json
          remove-stale-reports: true