name: Terraform Destroy (manual trigger)

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ vars.terraform_version }}
  
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform
  
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform